### PR TITLE
I have converted your PDF file to HTML

### PR DESCRIPTION
**Pull request by Aruna-Hewapathirane**
Please review and merge if useful. Thank you.

### CODE REVIEW

**Comment by ikelaiah** [comment]
Marged, thanks for this. 
I'm sorry for the slow response, I did not have internet about 2 days.

**Comment by ikelaiah** [comment]
By the way, I have just noticed the column name in the HTML page is not correct.

In the `Local Compiler` section, the heading should be `cmd`, `short`, `long` and `explanation`.

image

In the `Global Compiler` section, the heading should be `cmd`, `short`, `long` and `explanation`.

image

Would you mind revising these and do another PR? Many thanks.

-Iwan

**Comment by Aruna-Hewapathirane** [comment]
No worries. Hope your internet is better soon.

**Comment by Aruna-Hewapathirane** [comment]
Iwan, both sections have IDENTICAL column names. I am not sure what is not
correct.

**Comment by ikelaiah** [comment]
HI @Aruna-Hewapathirane ,

I'm sorry, I did not articulate myself clearly.
The original PDF has the following column name.

image

The converted HTML shows incorrect column names on two columns.

image

Thank you
-Iwan

**Pull request merged**
